# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property.
---
include:
  - board: seeeduino_xiao_rp2040
    shield: swoop_left
  - board: seeeduino_xiao_rp2040
    shield: swoop_right
